name: invoyo-dev

services:
  web:
    image: invoyo-api-dev-image
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: invoyo-api-dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/home/app/app
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    container_name: invoyo-db-dev
    environment:
      POSTGRES_DB: invoyo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: invoyo-redis-dev
    ports:
      - "6379:6379"
    networks:
      - app-network

  client:
    image: invoyo-client-dev-image
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: invoyo-client-dev
    ports:
      - "4200:4200"
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.angular
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data_dev:
